### ISSUE TITLE
Ansible Galaxy, debops.ferm package not found

### ISSUE THREAD

**Issue by Thaillie** [jsphpl/laravan#10]
While running the `./setup.sh` I ran into the problem that the package `debops.ferm` has been removed from the Ansible Galaxy.
For as far as I can find the package is still available on Github.

So would it be an easy fix to just point to the Github repo in the requirements file?

**Comment by jsphpl** [comment]
Thanks for reporting the issue!

I've filed an upstream issue (debops/ansible-ferm#118) and would like to await a response there, before changing any of our code.

**Comment by Thaillie** [comment]
Looks like the source repo wont be coming back as they went for a different release approach.
